language: java
sudo: false
addons:
  postgresql: 9.3
services:
  - couchdb
  - rabbitmq
before_script:
      - psql -c "ALTER USER postgres WITH PASSWORD 'password'" -U postgres
script:
  - javac -version
  - java -version
  - mvn --version
  - mvn clean test
after_success:
  - mvn clean jacoco:prepare-agent test jacoco:report coveralls:repor

