language: java
sudo: false
services:
  - couchdb
  - mysql
before_script:
      - mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('VA1913wm'); flush privileges;"
script:
  - javac -version
  - java -version
  - mvn --version
  - mvn clean test
