language: java
sudo: required
services:
  - couchdb
  - mysql
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('VA1913wm') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
script:
  - javac -version
  - java -version
  - mvn --version
  - mvn -X clean test
