language: java
sudo: false
services:
  - couchdb
  - mysql
install: echo "skip" # or anything that returns 0 status
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('VA1913wm') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - curl -X PUT http://localhost:5984/_config/admins/rootuser -d '"adminpass"'
script:
  - javac -version
  - java -version
  - mvn --version
  - mvn clean test
