language: java
sudo: false
services:
  - couchdb
  - mysql
install:
  - echo "skip" # or anything that returns 0 status
  - curl -X PUT http://localhost:5984
before_script:
  - curl -X PUT http://localhost:5984/_config/admins/opensrp -d '"opensrp"'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
script:
  - javac -version
  - java -version
  - mvn --version
  - mvn clean test
notifications:
  slack:
    secure: Ueku2w/RdSfh1zEDErTbHi+hRx154fH10ykGcfrXPXhTVtWopG73BGDRKfVgU1MCokEo+2jtkRAuJB29R1PV8E3845wWJFs9ZPGcl0rjfx3qP2G/bCuARRHmBJ33YStROvaVF3ppNjJau7VinIF3giem+4WgtQ8KPmqqviDg8Tw=
after_success:
  - mvn clean test jacoco:report coveralls:report 
