language: java
sudo: required
addons:
  postgresql: 9.3
services:
  - couchdb
  - rabbitmq
install:
  - ./travis_couchdb_lucene.sh
before_script:
      - psql -c "ALTER USER postgres WITH PASSWORD 'password'" -U postgres
      - curl -X PUT http://localhost:5984/_config/admins/opensrp -d '"opensrp"'
      - sudo service couchdb-lucene start
script:
  - javac -version
  - java -version
  - mvn --version
  - mvn clean test
