
language: java
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
addons:
  - postgresql: 9.3
  - mysql
services:
  - couchdb
  - rabbitmq
before_script:
  # set postgres password
  - psql -c "ALTER USER postgres WITH PASSWORD 'VA1913wm'" -U postgres
  # set mysql password 
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('VA1913wm') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -uroot -pVA1913wm -e "SELECT User, Host, plugin FROM mysql.user" mysql
script:
  - javac -version
  - java -version
  - mvn --version
  - mvn test
